repos:
  - repo: local
    hooks:
      - id: gitleaks-staged
        name: Detect hardcoded secrets
        entry: gitleaks git --pre-commit --staged --redact --verbose
        language: system
        pass_filenames: false
