ALTER TABLE hosts ADD COLUMN IF NOT EXISTS host_number BIGINT GENERATED ALWAYS AS IDENTITY;
ALTER TABLE hosts DROP CONSTRAINT IF EXISTS uq_hosts_host_number;
ALTER TABLE hosts ADD CONSTRAINT uq_hosts_host_number UNIQUE (host_number);
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS agent_name VARCHAR(255);
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS agent_path VARCHAR(1024);
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS agent_status VARCHAR(50) NOT NULL DEFAULT 'OFFLINE';
