ALTER TABLE hosts DROP COLUMN IF EXISTS agent_name;

ALTER TABLE hosts ADD COLUMN IF NOT EXISTS agent_id UUID;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS agent_id UUID;
ALTER TABLE host_parcels ADD COLUMN IF NOT EXISTS agent_id UUID;
ALTER TABLE cluster_services ADD COLUMN IF NOT EXISTS agent_id UUID;
