CREATE TABLE IF NOT EXISTS kf_external_clusters (
    id UUID PRIMARY KEY,
    cluster_name VARCHAR(255) NOT NULL,
    bootstrap_servers VARCHAR(255) NOT NULL,
    kafka_version VARCHAR(100),
    kafka_mode VARCHAR(50),
    kafka_cluster_id VARCHAR(100),
    security VARCHAR(50),
    broker_count INT,
    environment VARCHAR(100),
    install_path VARCHAR(512),
    log_dirs TEXT,
    listeners TEXT,
    advertised_listeners TEXT,
    process_roles TEXT,
    external_broker_hosts_json TEXT,
    cpu_usage_pct DOUBLE PRECISION,
    memory_used_mb BIGINT,
    memory_total_mb BIGINT,
    disk_used_gb BIGINT,
    disk_total_gb BIGINT,
    is_running BOOLEAN,
    status VARCHAR(50) DEFAULT 'PENDING',
    created_by VARCHAR(128) NOT NULL DEFAULT 'system',
    updated_by VARCHAR(128) NOT NULL DEFAULT 'system',
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
